pipeline {
    agent any
    environment {
        exitCode = 0
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/tomer265/wog'
            }
        }
        stage('Build'){
            steps {
                sh '''cd modules/score
                docker build . -t wogapi:latest'''
            }
        }
        stage('Run'){
            steps {
                sh 'docker run -d -p 8777:5000 --name wogapi wogapi:latest'
            }
        }
        stage('Test'){
            steps{
                script{
                    try{
                        exitCode = sh(script: 'python3 tests/e2e/e2e.py', returnStatus: true)
                        if (exitCode == 0){
                            echo "Tests passed successfully!"
                        }
                        else{
                            echo "Tests failed. View console for more details."
                        }
                    }
                    catch (Exception ex){
                        echo 'error running stage Test: ' + ex.toString()
                    }
                }
            }
        }
        stage('Finalize'){
            steps{
                echo 'stopping docker container "wogapi"'
                sh 'docker stop wogapi'
                script {
                    if (exitCode == 0){
                        echo 'Pushing container to docker hub...'
                        sh 'docker push tomer265/score-wogapi:latest'
                    }
                    else{
                        echo 'Test exit code 1 - not pushing to docker hub. Please check the logs.'
                    }
                }
            }
        }
    }
}
